export const STUPID_QUOTES = [
  "I never think of him / Except on midnights like this. — Taylor Swift",
  "God knows I tried, I tried to be someone. — Lana Del Rey",
  "Sometimes it lasts in love, but sometimes it hurts instead. — Adele",
  "I knew you were trouble when you walked in. — Taylor Swift",
  "What a shame we all became such fragile, broken things. — Paramore",
  "I'm not the only one who's been wrong. — Kelly Clarkson",
  "I've got thick skin and an elastic heart, but your blade might be too sharp. — Sia",
  "Isn’t it strange how we used to be strangers? — Olivia Rodrigo",
  "We were built to fall apart, then fall back together. — Taylor Swift",
  "I’m holding on, why is everything so heavy? — Linkin Park",
  "I'm just a notch in your bedpost, but you're just a line in a song. — Fall Out Boy",
  "I’m not okay, I promise. — My Chemical Romance",
  "I tear my heart open, I sew myself shut. — Papa Roach",
  "Let’s be alone together, we can stay young forever. — Fall Out Boy",
  "Don’t waste your time on me, you’re already the voice inside my head. — Blink-182",
  "If I'm just bad news, then you're a liar. — Taking Back Sunday",
  "All that I’m after is a life full of laughter, as long as I’m laughing with you. — Daughtry",
  "It's not a side effect of the cocaine, I'm thinking it must be love. — Panic! At The Disco",
  "I miss the days when I was young and not afraid. — Simple Plan",
  "I tried so hard and got so far, but in the end, it doesn’t even matter. — Linkin Park",
];
