/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticePuzzleIdRouteImport } from './routes/practice/$puzzleId'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticePuzzleIdRoute = PracticePuzzleIdRouteImport.update({
  id: '/$puzzleId',
  path: '/$puzzleId',
  getParentRoute: () => PracticeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/practice': typeof PracticeRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/practice/$puzzleId': typeof PracticePuzzleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/practice': typeof PracticeRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/practice/$puzzleId': typeof PracticePuzzleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/practice': typeof PracticeRouteWithChildren
  '/statistics': typeof StatisticsRoute
  '/practice/$puzzleId': typeof PracticePuzzleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cheatsheet'
    | '/practice'
    | '/statistics'
    | '/practice/$puzzleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cheatsheet' | '/practice' | '/statistics' | '/practice/$puzzleId'
  id:
    | '__root__'
    | '/'
    | '/cheatsheet'
    | '/practice'
    | '/statistics'
    | '/practice/$puzzleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheatsheetRoute: typeof CheatsheetRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  StatisticsRoute: typeof StatisticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$puzzleId': {
      id: '/practice/$puzzleId'
      path: '/$puzzleId'
      fullPath: '/practice/$puzzleId'
      preLoaderRoute: typeof PracticePuzzleIdRouteImport
      parentRoute: typeof PracticeRoute
    }
  }
}

interface PracticeRouteChildren {
  PracticePuzzleIdRoute: typeof PracticePuzzleIdRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticePuzzleIdRoute: PracticePuzzleIdRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheatsheetRoute: CheatsheetRoute,
  PracticeRoute: PracticeRouteWithChildren,
  StatisticsRoute: StatisticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
